conky.config = {
    alignment = 'top_right',
    gap_x = 35,
    gap_y = 50,
    minimum_width = 290,
    maximum_width = 310,

    update_interval = 1.0,
    total_run_times = 0,
    double_buffer = true,
    no_buffers = true,

    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

    use_xft = true,
    font = 'Monospace:size=9:bold',
    xftalpha = 1.0,

    default_color = '#f8fafc',
    color1 = '#00f0ff',
    color2 = '#a855f7',
    color3 = '#475569',

    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    draw_graph_borders = false,
}

conky.text = [[
${image /opt/cyber-welcome/avatar_clean.png -p 5,0 -s 52x72}
${goto 72}${color1}OPERATOR ${color3}───────────────${color}
${goto 72}${color2}USER:${color} SENE44
${goto 72}${color1}STATUS:${color} ACTIVE [ONLINE]
${goto 72}${color1}UPTIME:${color} ${uptime_short}

${voffset 8}${color1}CPU INTEL i5-2310 ${color3}────────────${color}
${color1}Core 1:${color} ${cpu cpu1}% ${alignr}${color2}${cpubar cpu1 6,150}
${color1}Core 2:${color} ${cpu cpu2}% ${alignr}${color2}${cpubar cpu2 6,150}
${color1}Core 3:${color} ${cpu cpu3}% ${alignr}${color2}${cpubar cpu3 6,150}
${color1}Core 4:${color} ${cpu cpu4}% ${alignr}${color2}${cpubar cpu4 6,150}

${color2}MEMORY & STORAGE ${color3}─────────────${color}
${color1}RAM:${color} $mem / $memmax ${alignr}${color2}${membar 6,130}
${color1}SSD:${color} ${fs_used /} / ${fs_size /} ${alignr}${color2}${fs_bar 6,130 /}

${color2}TRAFFIC I/O ${color3}──────────────────${color}
${color1}DL:${color} ${downspeed} ${alignr}${color1}UL:${color} ${upspeed}
${color3}${downspeedgraph 24,135 00f0ff a855f7} ${alignr}${color3}${upspeedgraph 24,135 00f0ff a855f7}
]]
